/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;


import controle.MedicoControle;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Medico;

/**
 *
 * @author joao
 */
public class FormListaMedico extends javax.swing.JFrame {

    /**
     * Creates new form FormListaMedico
     */
    public FormListaMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarMedico = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblListarMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome Completo", "Especialidade", "CPF", "Data de Nascimento", "Sexo", "Telefone", "Numero crm", "Data Cadastro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarMedico);
        if (tblListarMedico.getColumnModel().getColumnCount() > 0) {
            tblListarMedico.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<Medico> med = MedicoControle.ListarMedico();
        DefaultTableModel dtmMedico = (DefaultTableModel) tblListarMedico.getModel();
        for (Medico p : med) {
            String formato = "dd/MM/yyyy";
            DateFormat dateFormat = new SimpleDateFormat(formato);
            String[] dados = {String.valueOf(p.getId()),
                p.getNomeCompleto(),
                String.valueOf(p.getIdEspecialidades()),
                p.getCpf(),
                dateFormat.format(p.getDataNascimento()),
                p.getSexo(),
                "("+p.getDdd() + ") " + p.getTelefone(),
                p.getNumCrm(),
                dateFormat.format(p.getDataCadastro()),
            };
            dtmMedico.addRow(dados);
        }
        tblListarMedico.setModel(dtmMedico);
    }//GEN-LAST:event_formWindowOpened

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int med = Integer.parseInt(tblListarMedico.getValueAt(this.tblListarMedico.getSelectedRow(), 0).toString());
        Boolean apagou = MedicoControle.Excluir(med);

        if (apagou == true) { 

          getRecarregarLista();
                    
            JOptionPane.showMessageDialog(null,
                    "Medico Removido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null,
                    "Houve um erro na remoção do Medico!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void getRecarregarLista() {

        this.limpaTabela();
        List<Medico> med = MedicoControle.ListarMedico();
        DefaultTableModel dtmMedico = (DefaultTableModel) tblListarMedico.getModel();
        
        for (Medico p : med) {

            String formato = "dd/MM/yyyy";
            DateFormat dateFormat = new SimpleDateFormat(formato);
            String[] dados = {String.valueOf(p.getId()),
                p.getNomeCompleto(),
                String.valueOf(p.getIdEspecialidades()),
                p.getCpf(),
                dateFormat.format(p.getDataNascimento()),
                p.getSexo(),
                "("+p.getDdd() + ") " + p.getTelefone(),
                p.getNumCrm(),
                dateFormat.format(p.getDataCadastro()),
            
            };
            dtmMedico.addRow(dados);
        }
        tblListarMedico.setModel(dtmMedico);
        
    }
    public void limpaTabela() {
        DefaultTableModel tblRemove = (DefaultTableModel) tblListarMedico.getModel();
        int tamanho = tblRemove.getRowCount();
        if (tamanho > 0) {
            for (int i = tamanho - 1; i >= 0; i--) {
                tblRemove.removeRow(i);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarMedico;
    // End of variables declaration//GEN-END:variables
}
