/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;





/**
 *
 * @author joao
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
   
    public long idusuario;

 
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnEspecialidades = new javax.swing.JMenu();
        smnCadastrarEspecialidades = new javax.swing.JMenuItem();
        smnListarEspecialidades = new javax.swing.JMenuItem();
        mnMedicos = new javax.swing.JMenu();
        smnCadastrarMedicos = new javax.swing.JMenuItem();
        smnListarMedicos = new javax.swing.JMenuItem();
        mnPacientes = new javax.swing.JMenu();
        smnCadastrarPacientes = new javax.swing.JMenuItem();
        smnListarPacientes = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        smnCadastrarConsultas = new javax.swing.JMenuItem();
        smnListarConsultas = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("MENU");

        mnEspecialidades.setText("Especialidades");

        smnCadastrarEspecialidades.setText("Cadastrar");
        smnCadastrarEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnCadastrarEspecialidadesActionPerformed(evt);
            }
        });
        mnEspecialidades.add(smnCadastrarEspecialidades);

        smnListarEspecialidades.setText("Listar");
        smnListarEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnListarEspecialidadesActionPerformed(evt);
            }
        });
        mnEspecialidades.add(smnListarEspecialidades);

        jMenuBar1.add(mnEspecialidades);

        mnMedicos.setText("Medicos");

        smnCadastrarMedicos.setText("Cadastrar");
        smnCadastrarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnCadastrarMedicosActionPerformed(evt);
            }
        });
        mnMedicos.add(smnCadastrarMedicos);

        smnListarMedicos.setText("Listar");
        smnListarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnListarMedicosActionPerformed(evt);
            }
        });
        mnMedicos.add(smnListarMedicos);

        jMenuBar1.add(mnMedicos);

        mnPacientes.setText("Pacientes");
        mnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPacientesActionPerformed(evt);
            }
        });

        smnCadastrarPacientes.setText("Cadastrar");
        smnCadastrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnCadastrarPacientesActionPerformed(evt);
            }
        });
        mnPacientes.add(smnCadastrarPacientes);

        smnListarPacientes.setText("Listar");
        smnListarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnListarPacientesActionPerformed(evt);
            }
        });
        mnPacientes.add(smnListarPacientes);

        jMenuBar1.add(mnPacientes);

        mnConsultas.setText("Consultas");

        smnCadastrarConsultas.setText("Cadastrar");
        smnCadastrarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnCadastrarConsultasActionPerformed(evt);
            }
        });
        mnConsultas.add(smnCadastrarConsultas);

        smnListarConsultas.setText("Listar");
        smnListarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnListarConsultasActionPerformed(evt);
            }
        });
        mnConsultas.add(smnListarConsultas);

        jMenuBar1.add(mnConsultas);

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnCadastrarEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnCadastrarEspecialidadesActionPerformed
        FormCadEspecialidades esp = new FormCadEspecialidades();
        esp.setVisible(true);
    }//GEN-LAST:event_smnCadastrarEspecialidadesActionPerformed

    private void smnCadastrarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnCadastrarMedicosActionPerformed
        FormCadMedico med = new FormCadMedico();
        med.setVisible(true);
    }//GEN-LAST:event_smnCadastrarMedicosActionPerformed

    private void smnCadastrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnCadastrarPacientesActionPerformed
        FormCadPaciente formpac = new FormCadPaciente();
        formpac.setVisible(true);
    }//GEN-LAST:event_smnCadastrarPacientesActionPerformed

    private void smnCadastrarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnCadastrarConsultasActionPerformed
        FormCadConsulta formc = new FormCadConsulta();
        formc.setVisible(true);
        formc.idusuario = this.idusuario;
    }//GEN-LAST:event_smnCadastrarConsultasActionPerformed

    private void smnListarEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnListarEspecialidadesActionPerformed
       FormListaEspecialidades forml = new FormListaEspecialidades();
       forml.setVisible(true);
    }//GEN-LAST:event_smnListarEspecialidadesActionPerformed

    private void smnListarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnListarMedicosActionPerformed
        FormListaMedico formmed = new FormListaMedico();
        formmed.setVisible(true);
    }//GEN-LAST:event_smnListarMedicosActionPerformed

    private void mnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPacientesActionPerformed
        
    }//GEN-LAST:event_mnPacientesActionPerformed

    private void smnListarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnListarPacientesActionPerformed
        FormListaPaciente formlipac = new FormListaPaciente();
        formlipac.setVisible(true);
    }//GEN-LAST:event_smnListarPacientesActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    private void smnListarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnListarConsultasActionPerformed
       FormListaConsulta formlc = new FormListaConsulta();
       formlc.setVisible(true);
       formlc.idusuario = this.idusuario;
    }//GEN-LAST:event_smnListarConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnEspecialidades;
    private javax.swing.JMenu mnMedicos;
    private javax.swing.JMenu mnPacientes;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem smnCadastrarConsultas;
    private javax.swing.JMenuItem smnCadastrarEspecialidades;
    private javax.swing.JMenuItem smnCadastrarMedicos;
    private javax.swing.JMenuItem smnCadastrarPacientes;
    private javax.swing.JMenuItem smnListarConsultas;
    private javax.swing.JMenuItem smnListarEspecialidades;
    private javax.swing.JMenuItem smnListarMedicos;
    private javax.swing.JMenuItem smnListarPacientes;
    // End of variables declaration//GEN-END:variables
}
